electrodes = {
	'Fp1' : 1,
	'Fp2' : 2,
	'F3'  : 3,
	'F4'  : 4,
	'C3'  : 5,
	'C4'  : 6,
	'P3'  : 7,
	'P4'  : 8,
	'O1'  : 9,
	'O2'  : 10,
	'A1'  : 11,
	'A2'  : 12,
	'F7'  : 13,
	'F8'  : 14,
	'T3'  : 15,
	'T4'  : 16,
	'T5'  : 17,
	'T6'  : 18,
	'Fz'  : 19,
	'Cz'  : 20,
	'Pz'  : 21,
	'X3'  : 22,
	1     : 'Fp1',
	2     : 'Fp2',
	3     : 'F3',
	4     : 'F4',
	5     : 'C3',
	6     : 'C4',
	7     : 'P3',
	8     : 'P4',
	9     : 'O1',
	10    : 'O2',
	11    : 'A1',
	12    : 'A2',
	13    : 'F7',
	14    : 'F8',
	15    : 'T3',
	16    : 'T4',
	17    : 'T5',
	18    : 'T6',
	19    : 'Fz',
	20    : 'Cz',
	21    : 'Pz',
	22    : 'X3',
}

CLA = {
	'LH' : 1,
	'RH' : 2,
	'O'  : 3,
	'initial relaxation period'  : 99,
	'inter-session rest break period'  : 91,
	'experiment end'  : 92,
	1    : 'LH',
	2    : 'RH',
	3    : 'O' ,
	99   : 'initial relaxation period',
	91   : 'inter-session rest break period',
	92   : 'experiment end',	
}

HaLT = {
	'LH' : 1,
	'RH' : 2,
	'O'  : 3,
	'Ll' : 4,
	'T'  : 5,
	'Rl' : 6, 
	'initial relaxation period'  : 99,
	'inter-session rest break period'  : 91,
	'experiment end'  : 92,
	1    : 'LH',
	2    : 'RH',
	3    : 'O' ,
	4    : 'Ll',
	5    : 'T' ,
	6    : 'Rl',
	99   : 'initial relaxation period',
	91   : 'inter-session rest break period',
	92   : 'experiment end',	
}

fiveF = {
	'thumb' : 1,
	'index' : 2,
	'middle'  : 3,
	'ring' : 4,
	'pinkie'  : 5,
	'initial relaxation period'  : 99,
	'inter-session rest break period'  : 91,
	'experiment end'  : 92,
	1    : 'thumb',
	2    : 'index',
	3    : 'middle' ,
	4    : 'ring',
	5    : 'pinkie' ,
	99   : 'initial relaxation period',
	91   : 'inter-session rest break period',
	92   : 'experiment end',	
}

translator = {
	'electrodes' : electrodes,
	'E' : electrodes,
	'CLA' : CLA,
	'5F' : fiveF
}
